import {
  GiftIcon,
  TvIcon,
  MailIcon,
  ThumbsDownIcon,
  DownloadCloudIcon,
  CameraIcon,
  VolumeDownIcon,
  WatchIcon,
  CloudSnowIcon,
  ActivityIcon,
  FlagIcon,
  MessageCircleIcon,
  VolumeOnIcon,
  PinIcon,
  CoffeeIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  BookOpenIcon,
  TruckIcon,
  ThumbsUpIcon,
  UmbrellaIcon,
  MicIcon,
  MapIcon,
  HeartIcon,
  RadioIcon,
  BellIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BookIcon,
} from "./AnimatedIcons";

// STATIC ICONS * * * * * * * * *
import {
  GiftIconStatic,
  TvIconStatic,
  MailIconStatic,
  ThumbsDownIconStatic,
  DownloadCloudIconStatic,
  CameraIconStatic,
  VolumeDownIconStatic,
  WatchIconStatic,
  CloudSnowIconStatic,
  ActivityIconStatic,
  FlagIconStatic,
  MessageCircleIconStatic,
  VolumeOnIconStatic,
  PinIconStatic,
  CoffeeIconStatic,
  ChevronDownIconStatic,
  ChevronLeftIconStatic,
  ChevronRightIconStatic,
  ChevronUpIconStatic,
  BookOpenIconStatic,
  TruckIconStatic,
  ThumbsUpIconStatic,
  UmbrellaIconStatic,
  MicIconStatic,
  MapIconStatic,
  HeartIconStatic,
  RadioIconStatic,
  BellIconStatic,
  ArrowDownIconStatic,
  ArrowLeftIconStatic,
  ArrowRightIconStatic,
  ArrowUpIconStatic,
  BookIconStatic,
} from "./StaticIcons";

const iconsData = [
  { icon: TvIcon, name: "TV", category: "Devices", staticIcon: TvIconStatic },
  { icon: MailIcon, name: "mail", category: "", staticIcon: MailIconStatic },
  { icon: GiftIcon, name: "gift", category: "Real World", staticIcon: GiftIconStatic },
  {
    icon: ThumbsDownIcon,
    name: "thumbs-down",
    category: "Actions",
    staticIcon: ThumbsDownIconStatic,
  },
  {
    icon: DownloadCloudIcon,
    name: "download-cloud",
    category: "Data",
    staticIcon: DownloadCloudIconStatic,
  },
  {
    icon: CameraIcon,
    name: "camera",
    category: "Devices",
    staticIcon: CameraIconStatic,
  },
  {
    icon: VolumeDownIcon,
    name: "volume-off",
    category: "Media",
    staticIcon: VolumeDownIconStatic,
  },
  { icon: WatchIcon, name: "watch", category: "Devices", staticIcon: WatchIconStatic },
  {
    icon: CloudSnowIcon,
    name: "cloud-snow",
    category: "Weather",
    staticIcon: CloudSnowIconStatic,
  },
  {
    icon: ActivityIcon,
    name: "activity",
    category: "Data",
    staticIcon: ActivityIconStatic,
  },
  { icon: FlagIcon, name: "flag", category: "Communications", staticIcon: FlagIconStatic },
  {
    icon: MessageCircleIcon,
    name: "message-circle",
    category: "Action",
    staticIcon: MessageCircleIconStatic,
  },
  {
    icon: VolumeOnIcon,
    name: "volume-on",
    category: "Media",
    staticIcon: VolumeOnIconStatic,
  },
  { icon: PinIcon, name: "pin", category: "Geo", staticIcon: PinIconStatic },
  {
    icon: CoffeeIcon,
    name: "coffee",
    category: "Real World",
    staticIcon: CoffeeIconStatic,
  },
  {
    icon: ChevronDownIcon,
    name: "chevron-down",
    category: "Arrows",
    staticIcon: ChevronDownIconStatic,
  },
  {
    icon: ChevronUpIcon,
    name: "chevron-up",
    category: "Arrows",
    staticIcon: ChevronUpIconStatic,
  },
  {
    icon: BookOpenIcon,
    name: "book-open",
    category: "Real World",
    staticIcon: BookOpenIconStatic,
  },
  { icon: TruckIcon, name: "truck", category: "Commerce", staticIcon: TruckIconStatic },
  {
    icon: ThumbsUpIcon,
    name: "thumbs-up",
    category: "Actions",
    staticIcon: ThumbsUpIconStatic,
  },
  {
    icon: UmbrellaIcon,
    name: "umbrella",
    category: "Weather",
    staticIcon: UmbrellaIconStatic,
  },
  {
    icon: ArrowRightIcon,
    name: "arrow-right",
    category: "Arrows",
    staticIcon: ArrowRightIconStatic,
  },
  {
    icon: ArrowUpIcon,
    name: "arrow-up",
    category: "Arrows",
    staticIcon: ArrowUpIconStatic,
  },
  { icon: MicIcon, name: "mic", category: "Media", staticIcon: MicIconStatic },
  { icon: MapIcon, name: "map", category: "Geo", staticIcon: MapIconStatic },
  { icon: HeartIcon, name: "heart", category: "Shapes", staticIcon: HeartIconStatic },
  {
    icon: ChevronLeftIcon,
    name: "chevron-left",
    category: "Arrows",
    staticIcon: ChevronLeftIconStatic,
  },
  {
    icon: ChevronRightIcon,
    name: "chevron-right",
    category: "Arrows",
    staticIcon: ChevronRightIconStatic,
  },
  { icon: RadioIcon, name: "radio", category: "Media", staticIcon: RadioIconStatic },
  { icon: BellIcon, name: "bell", category: "Communications", staticIcon: BellIconStatic },
  {
    icon: ArrowDownIcon,
    name: "arrow-down",
    category: "Arrows",
    staticIcon: ArrowDownIconStatic,
  },
  {
    icon: ArrowLeftIcon,
    name: "arrow-left",
    category: "Arrows",
    staticIcon: ArrowLeftIconStatic,
  },
  { icon: BookIcon, name: "book", category: "Real World", staticIcon: BookIconStatic },
];

export default iconsData;
